//go:build ignore
// +build ignore

// Directive code generator for SecurePrompt.
//
// Usage:
//  1. Annotate functions with // @Policy(...) comments:
//
//     // @Policy(profile="strict", block=true, rewrite=true)
//     func myPrompt(ctx context.Context, input Input) (string, error) { ... }
//
//  2. Run: go generate ./...
//
//  3. Generated code creates wrapped variables:
//     var myPrompt = directive.Apply(myPromptImpl, directive.PolicyConfig{...})
//
// This is optional—the functional wrapper approach works without code generation.
package main

import (
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"text/template"
)

var (
	dir         = flag.String("dir", ".", "Directory to scan for @Policy annotations")
	output      = flag.String("out", "directive_generated.go", "Output file for generated wrappers")
	packageName = flag.String("pkg", "directive", "Package name for generated code")
)

// PolicyAnnotation represents a parsed @Policy comment.
type PolicyAnnotation struct {
	FunctionName string
	FunctionSig  string
	Profile      string
	Block        bool
	Rewrite      bool
	RemoteURL    string
	OriginalBody string
}

// Template for generated wrapper code.
const wrapperTemplate = `// Code generated by go generate; DO NOT EDIT.
// Source: {{.FunctionName}}
// Generated by: directive/generate.go

package {{.PackageName}}

import (
	"context"
	{{if .RemoteURL}}"os"{{end}}
)

// {{.FunctionName}}Impl is the original function implementation.
{{.FunctionSig}} {
{{.OriginalBody}}
}

// {{.FunctionName}} is the policy-wrapped version.
// Auto-generated by directive code generator.
var {{.FunctionName}} = Apply(
	{{.FunctionName}}Impl,
	PolicyConfig{
		{{if .Profile}}Profile: "{{.Profile}}",{{end}}
		{{if .Block}}BlockOnViolation: {{.Block}},{{end}}
		{{if .Rewrite}}AllowRewrite: {{.Rewrite}},{{end}}
		{{if .RemoteURL}}RemoteOverrideURL: {{.RemoteURL}},{{end}}
	},
)
`

func main() {
	flag.Parse()

	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, *dir, func(info os.FileInfo) bool {
		return !strings.HasSuffix(info.Name(), "_test.go") &&
			!strings.HasSuffix(info.Name(), "_generated.go")
	}, parser.ParseComments)
	if err != nil {
		fmt.Fprintf(os.Stderr, "parse error: %v\n", err)
		os.Exit(1)
	}

	var annotations []PolicyAnnotation
	policyRe := regexp.MustCompile(`//\s*@Policy\(([^)]+)\)`)
	configRe := regexp.MustCompile(`(\w+)\s*=\s*"([^"]+)"|(\w+)\s*=\s*(true|false)`)

	for _, pkg := range pkgs {
		for _, file := range pkg.Files {
			for _, decl := range file.Decls {
				fn, ok := decl.(*ast.FuncDecl)
				if !ok || fn.Doc == nil {
					continue
				}

				for _, comment := range fn.Doc.List {
					if matches := policyRe.FindStringSubmatch(comment.Text); len(matches) > 1 {
						config := parsePolicyConfig(matches[1], configRe)
						sig := formatFuncSignature(fn)
						body := formatFuncBody(fn)

						annotations = append(annotations, PolicyAnnotation{
							FunctionName: fn.Name.Name,
							FunctionSig:  sig,
							OriginalBody: body,
							Profile:      config["profile"],
							Block:        config["block"] == "true",
							Rewrite:      config["rewrite"] == "true",
							RemoteURL:    config["remote"],
						})
					}
				}
			}
		}
	}

	if len(annotations) == 0 {
		fmt.Println("No @Policy annotations found. Nothing to generate.")
		return
	}

	tmpl := template.Must(template.New("wrapper").Parse(wrapperTemplate))
	outFile, err := os.Create(filepath.Join(*dir, *output))
	if err != nil {
		fmt.Fprintf(os.Stderr, "create output error: %v\n", err)
		os.Exit(1)
	}
	defer outFile.Close()

	for _, ann := range annotations {
		data := struct {
			PolicyAnnotation
			PackageName string
		}{
			PolicyAnnotation: ann,
			PackageName:      *packageName,
		}
		if err := tmpl.Execute(outFile, data); err != nil {
			fmt.Fprintf(os.Stderr, "template error: %v\n", err)
			os.Exit(1)
		}
	}

	fmt.Printf("Generated %d policy wrappers to %s\n", len(annotations), *output)
}

func parsePolicyConfig(configStr string, re *regexp.Regexp) map[string]string {
	result := make(map[string]string)
	matches := re.FindAllStringSubmatch(configStr, -1)
	for _, match := range matches {
		if match[1] != "" {
			result[match[1]] = match[2]
		} else if match[3] != "" {
			result[match[3]] = match[4]
		}
	}
	return result
}

func formatFuncSignature(fn *ast.FuncDecl) string {
	params := formatFieldList(fn.Type.Params)
	results := ""
	if fn.Type.Results != nil {
		results = " " + formatFieldList(fn.Type.Results)
	}
	return fmt.Sprintf("func %s%s%s", fn.Name.Name, params, results)
}

func formatFieldList(fl *ast.FieldList) string {
	if fl == nil {
		return "()"
	}
	var parts []string
	for _, field := range fl.List {
		names := make([]string, len(field.Names))
		for i, name := range field.Names {
			names[i] = name.Name
		}
		typeStr := "any"
		if len(names) > 0 {
			parts = append(parts, fmt.Sprintf("%s %s", strings.Join(names, ", "), typeStr))
		} else {
			parts = append(parts, typeStr)
		}
	}
	return "(" + strings.Join(parts, ", ") + ")"
}

func formatFuncBody(fn *ast.FuncDecl) string {
	if fn.Body == nil {
		return "\t// No implementation"
	}
	return "\t// Original implementation preserved\n\t// ... (see source file)"
}
